name: Deploy pynb-dag-runner static website
description: NA

on:
  workflow_call:
    inputs:
      a_parameter:
        description: test parameters
        required: false
        #default: foo
        type: string

      pynb_dag_runner_ref:
        #description: Version of pynb-dag-runner to install
        required: false
        #default: pynb-dag-runner-snapshot
        type: string

#outputs:
#  one-output-value:
#    description: Description about output value

jobs:
  deploy-static-website:
    runs-on: ubuntu-20:04
    timeout-minutes: 25

    steps:
    - shell: bash
      run: echo Hello
