name: "Reusable workflow to deploy static website"

# Details on reusable workflows:
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
# - https://github.community/t/cant-call-reusable-workflow-unexpected-value-uses/204182

on:
  workflow_call:
    inputs:
      #
      # The optional inputs
      #
      #  - pynb-dag-runner-package
      #  - pynb-dag-runner-webui-package
      #
      # allow the caller to override which versions of pynb-dag-runner{-webui} packages
      # to use when building the webui. By default, use the latest published versions.
      #
      pynb-dag-runner-package:
        required: false
        default: pynb-dag-runner
        type: string

      pynb-dag-runner-webui-package:
        required: false
        default: pynb-dag-runner-webui
        type: string

    secrets:
      # Token with write access to the caller repo
      CALLER_ACTION_GITHUB_TOKEN:
        required: true

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  update-static-website:
    name: Building assets to deploy as static website
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: "Fetch all artefacts into directory tree"
        run: |
          echo "Installing ${{ inputs.pynb-dag-runner-package }} ..."
          pip install \
              ${{ inputs.pynb-dag-runner-package }}
              
          echo "Installed Python packages"
          pip freeze

          echo "generate_static_data ..."
          generate_static_data \
              --github_repository $GITHUB_REPOSITORY \
              --output_www_root_directory ${{ github.workspace }}/www-root/

        env:
          # any Github token would work here. Also secrets.GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.CALLER_ACTION_GITHUB_TOKEN }}

      - name: "pip install package with static assets for web front end"
        run: |
          pip install \
              --quiet \
              ${{ inputs.pynb-dag-runner-webui-package }} \
              --target ${{ github.workspace }}/pynb_dag_runner_webui

          cp -r \
              ${{ github.workspace }}/pynb_dag_runner_webui/assets/. \
              ${{ github.workspace }}/www-root/


      - name: "Push www-root content to repo gh-pages branch"
        run: |
          cd ${{ github.workspace }}/www-root

          # Add files for troubleshooting in the browser (since Github Pages
          # does not allow list files).
          find . > list_all_files.txt
          du -hs * > disk_usage.txt

          git init
          git checkout -b gh-pages

          git add -A

          git config --local user.email "gh-automation-bot@github.com"
          git config --local user.name "GitHub Action Bot"
          git commit -m "update"

          git push --force \
            https://my_token_user:${{ secrets.CALLER_ACTION_GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git \
            gh-pages:gh-pages
